language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - jruby-1.7.25
  - jruby-9.1.7.0
  - ruby-head
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v "< 2"

services:
  - redis-server